---
- name: Ensure the group exists
  ansible.builtin.group:
    name: "{{ group_name }}"
    state: present

- name: Ensure users exist and are added to groups
  ansible.builtin.user:
    name: "{{ item }}"
    groups: "{{ group_name }},wheel"
    append: yes
    state: present
  loop: "{{ users }}"

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "/home/{{ item }}/.ssh"
    state: directory
    owner: "{{ item }}"
    group: "{{ group_name }}"
    mode: '0755'
  loop: "{{ users }}"
  become_user: "{{ item }}"

- name: Generate SSH keys for users
  ansible.builtin.command:
    cmd: ssh-keygen -t rsa -b 2048 -f /home/{{ item }}/.ssh/id_rsa -N ""
    creates: /home/{{ item }}/.ssh/id_rsa
  loop: "{{ users }}"
  become_user: "{{ item }}"

- name: Check if SSH private key exists for user100
  ansible.builtin.stat:
        path: "/home/user100/.ssh/id_rsa"
  register: ssh_key_stat

- name: Debug SSH key status
  ansible.builtin.debug:
        msg: "SSH key for user100 exists: {{ ssh_key_stat.stat.exists }}"

- name: Fetch SSH private key for user100
  fetch:
    src: "/home/user100/.ssh/id_rsa"
    dest: "/tmp/id_rsa_user100"
    flat: yes
  become: false
  delegate_to: localhost
  register: fetch_result
  failed_when: fetch_result.failed and fetch_result.msg != "the remote file does not exist, not transferring, ignored"

